import 'dart:async';
import 'dart:io';

import 'package:auto_hyphenating_text/auto_hyphenating_text.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_autofill_service/flutter_autofill_service.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_pdfview/flutter_pdfview.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:northguard/authentication/bloc/authentication.dart' as auth;
import 'package:northguard/config/configuration_bloc.dart';
import 'package:northguard/constants/colors.dart';
import 'package:northguard/constants/global_variables.dart';
import 'package:northguard/constants/preferences.dart';
import 'package:northguard/model/attachment.dart';
import 'package:northguard/model/filter.dart';
import 'package:northguard/model/location.dart';
import 'package:northguard/model/password.dart';
import 'package:northguard/model/pcrypt_key.dart';
import 'package:northguard/model/team.dart';
import 'package:northguard/passwords/bloc/file_viewer.dart' as file_viewer;
import 'package:northguard/passwords/bloc/password_edit.dart' as pass_edit;
import 'package:northguard/passwords/bloc/passwords.dart' as pass;
import 'package:northguard/passwords/presentation/widgets/address_drawer.dart';
import 'package:northguard/passwords/presentation/widgets/location_drawer.dart';
import 'package:northguard/passwords/presentation/widgets/password_edit_body.dart';
import 'package:northguard/passwords/presentation/widgets/passwords_app_bar.dart';
import 'package:northguard/passwords/presentation/widgets/passwords_list.dart';
import 'package:northguard/passwords/presentation/widgets/tags_drawer.dart';
import 'package:northguard/sharing/index.dart';
import 'package:northguard/util/formatters.dart';
import 'package:northguard/util/location_service.dart';
import 'package:northguard/util/settings.dart';
import 'package:northguard/util/strings.dart';
import 'package:northguard/web/server_adapter.dart';
import 'package:northguard/widget/custom_widgets.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:url_launcher/url_launcher.dart' as http;

part 'presentation/screens/file_viewer_screen.dart';
part 'presentation/screens/location_viewer_screen.dart';
part 'presentation/screens/password_details_screen.dart';
part 'presentation/screens/password_edit_screen.dart';
part 'presentation/screens/passwords_screen.dart';
